# .travis.yml
language: php

php:
  - 5.5

sudo: false

addons:
  apt:
    packages:
      - parallel

before_install:
  - gem update --system
  - gem install bundler
  - gem --version

script:
  - "bundle install"

after_success:
  - "bundle exec cap production deploy"