# .travis.yml
language: 
  - php
  - ruby

rvm:
  - 2.2

sudo: false

addons:
  apt:
    packages:
      - parallel

script:
  - "bundle install"

after_success:
  - "bundle exec cap production deploy"