# .travis.yml
language: php

branches:
  only:
    - master

php:
  - 5.6

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - \curl -sSL https://get.rvm.io | bash -s stable
  - rvm reload
  - rvm install ruby-2.3.0
  - rvm --default use ruby-2.3.0

script:
  - "bundle install"

after_success:
  - "bundle exec cap production deploy"