# .travis.yml
language: php

php:
  - 5.5

before_install:
  - sudo apt-get update
  - sudo apt-get install ruby2.0
  - ruby --version
  - gem install bundler 

script:
  - "bundle install"

after_success:
  - "bundle exec cap production deploy"