# .travis.yml
language: php

php:
  - 5.5

sudo: false

addons:
  apt:
    packages:
      - parallel

before_install:
  - sudo apt-get update
  - sudo apt-get install ruby
  - gem install bundler

script:
  - "bundle install"

after_success:
  - "bundle exec cap production deploy"